#!/usr/bin/env bash
set -e
[ -n "${SLSENV_DEBUG}" ] && set -x
source ${SLSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: slsenv list-remote" 1>&2
  exit 1
fi

platform="$(sls_platform)"
(( "$?" )) && exit $?

# This is a bit hacky since it's relying on the formatting of URLs
# returned in JSON output from the github API, but there's no other
# reasonable way to get a list of the current sls versions using
# only curl + POSIX tools
json=$(curlw -s -L https://api.github.com/repos/kubernetes/sls/releases)
(( "$?" )) && exit $?

echo "$json" \
  | grep 'download/[0-9\.]\{1,\}/sls-'$platform'"' \
  | sed 's/^.*download\///; s/\/.*$//' \
  | sort -t. -rn -k1,1 -k2,2 -k3,3 -k4,4 \
  | uniq

