#!/usr/bin/env bash
#
# Summary: Run an executable with the selected sls version
#
# Usage: slsenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected sls
# version's `bin' directory is at the front.
#

set -e
[ -n "${SLSENV_DEBUG}" ] && set -x

export SLSENV_VERSION="$(slsenv-version-name)"
SLS_BIN_PATH="${SLSENV_ROOT}/versions/${SLSENV_VERSION}/bin/sls"
export PATH="${SLS_BIN_PATH}:${PATH}"
"${SLS_BIN_PATH}" "${@}"
