#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Kops version
#
# Usage: slsenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Kops
# version's `bin' directory is at the front.
#
# For example, if the currently selected Kops version is 0.7.0:
#   slsenv exec plan
#
# is equivalent to:
#   PATH="$SLSENV_ROOT/versions/0.7.0/bin:$PATH" sls plan

set -e
[ -n "${SLSENV_DEBUG}" ] && set -x

export SLSENV_VERSION="$(slsenv-version-name)"
SLS_BIN_PATH="${SLSENV_ROOT}/versions/${SLSENV_VERSION}/bin/sls"
export PATH="${SLS_BIN_PATH}:${PATH}"
"${SLS_BIN_PATH}" "${@}"
