#!/usr/bin/env bash

[ -n "${SLSENV_DEBUG}" ] && set -x
source ${SLSENV_ROOT}/libexec/helpers

[ ${#} -ne 1 ] && error_and_die "usage: slsenv use <version>"

declare version_requested version regex

version_requested="${1}"

if [[ "${version_requested}" =~ ^min-required$ ]]; then
  echo "Detecting minimal required version..."
  found_min_required="$(slsenv-min-required)"

  if [[ $? -eq 0 ]]; then
      echo "Min required version is detected as ${found_min_required}"
      version_requested=${found_min_required}
  else
    exit 1
  fi
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -d "${SLSENV_ROOT}/versions" ] \
  || error_and_die "No versions of sls installed. Please install one with: slsenv install"

version="$(\ls "${SLSENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

[ -n "${version}" ] || error_and_die "No installed versions of sls matched '${1}'"

target_path=${SLSENV_ROOT}/versions/${version}/bin
[ -f ${target_path}/sls ] \
  || error_and_die "Version directory for ${version} is present, but the sls binary is not! Manual intervention required."
[ -x ${target_path}/sls ] \
  || error_and_die "Version directory for ${version} is present, but the sls binary is not executable! Manual intervention required. "

info "Switching to v${version}"
echo "${version}" > "$(slsenv-version-file)" || error_and_die "'switch to v${version} failed'"
sls --version 1>/dev/null || error_and_die "'sls --version' failed. Something is seriously wrong"
info "Switching completed"
