#!/usr/bin/env bash
set -e
[ -n "${SLSENV_DEBUG}" ] && set -x
source ${SLSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: slsenv list-remote" 1>&2
  exit 1
fi

platform="$(sls_platform)"
(( "$?" )) && exit $?

# This is a bit hacky since it's relying on the formatting of URLs
# returned in JSON output from the github API, but there's no other
# reasonable way to get a list of the current sls versions using
# only curl + POSIX tools
git ls-remote https://github.com/serverless/serverless.git \
  | grep -v '\^' \
  | awk '/refs\/tags/{ print $2}' \
  | grep -v '-' \
  | awk -F / '{print $3}' \
  | grep -ve '^v\.' \
  | sort --version-sort --reverse \
  | uniq
