#!/usr/bin/env bash
set -e
[ -n "${SLSENV_DEBUG}" ] && set -x
source ${SLSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: slsenv list-remote" 1>&2
  exit 1
fi

platform="$(sls_platform)"
(( "$?" )) && exit $?

versions=$(git ls-remote https://github.com/serverless/serverless.git \
  | grep -v '\^' \
  | awk '/refs\/tags/{ print $2}' \
  | grep -v '-' \
  | awk -F / '{print $3}' \
  | grep -ve '^v\.' \
  | sort --version-sort --reverse \
  | uniq)

# Binary exists above v1.57.0 in GitHub Releases
echo "$versions" | head -n $(echo "$versions" | grep -n 'v1.57.0' | cut -d':' -f1)
