#!/usr/bin/env bash

[ -n "${SLSENV_DEBUG}" ] && set -x
source ${SLSENV_ROOT}/libexec/helpers

[ ${#} -ne 0 ] \
  && error_and_die "usage: slsenv list"

[ -d "${SLSENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: slsenv install"

[[ -x "${SLSENV_ROOT}/versions" && -r "${SLSENV_ROOT}/versions" ]] \
  || error_and_die "slsenv versions directory is inaccessible!"

print_version () {
    if [ "$1" == "$(slsenv-version-name)" ]; then
        echo "* $1 (set by $(slsenv-version-file))"
    else
        echo "  $1"
    fi
}

for local_version in $(ls -1 "${SLSENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3); do
    print_version ${local_version}
done
