#!/usr/bin/env bash

[ -n "${SLSENV_DEBUG}" ] && set -x

echo "Usage: slsenv <command> [<options>]

Commands:
   install       Install a specific version of sls
   use           Switch a version to use
   uninstall     Uninstall a specific version of sls
   list          List all installed versions
   list-remote   List all installable versions
"
